### ISSUE TITLE
backend pc code to manage rolling code

### ISSUE THREAD

**Issue by welverin** [hardcodedpassword/rflink-alt#1]
Hi,
your project is very interesting, I have been using rflink for some years  and I wonder if the management of the rolling codes present in many devices will have to be developed in a software on rasperry / pc or on arduino as now ?
because this could solve some problems with the protocols not supported today by rflink
thank you
Leo

**Comment by hardcodedpassword** [comment]
Hi Leo,

Thanks for your message.

The reasons why I started this project was that rflink is not open source and did not support one of the devices I am using.

For this RFLink-alt the design was made to have the arduino code as simple as possible with high temporal accuracy. (I found the timing of the original RFLink to be rather inaccurate which led to problems that sometimes a signal was not interpreted right).

With this in mind the host (i.e. the PC, raspberry pi etc...) is responsible for decoding and encoding messages. Rolling codes like used in Somfy protocol need to be managed in the host.

With kind regards,

Martin
